import { TrollConfig } from './TrollClient';

export const config: TrollConfig = {
  troll: '<:troll:891744450752163891>',
  suffix: '<:troll:891744450752163891>',
  cake: '<:cakeday:874408986936492082>',
  coin: '<:rcoin:876254633813749780>',
  reddit: [
    '<:rsilver:843164309735735316>',
    '<:rgold:843160855234215968>',
    '<:rplat:843164215786340442>',
    '<:wholesome:843164215346069546>'
  ],
  general: '840829257004875789',
  responses: [ // These should probably be called 'triggers' instead 
    // if anyone wants to rewrite these regexes PLEASE PR holy shit they're bad
    [/\b(y((o+u('|’)?r+e?)|(o+|e|a))( +are)? +m((o+ther+)|(o+|u)m)(m+y+)?)/gi, 'i am doing your mother', './images/mother.png'],
    [/\b((amo+n?g+)|s+u+s+|impost|vent|pretender|cre+wma+te|medbay|electrical)/gi, 'SUSSY!', './images/amogsus.png'],
    [/.{500,}/g, ' ', './images/myreaction.png'],
  ],
  botRole: '841267799787438090',
  memberRole: '841295461486428200',
  adminRole: '842802299675213824',
  modRole: '842802567499219005',

  eightball: [
    'oh yeah',
    'i think so',
    '💯',
    'on god',
    'sure',
    'yass',
    'methinks yes',
    '<:ben:948262294402531348> yes', // ben
    'sorry im busy gaming ttyl',
    'not now',
    'ratio',
    'bro i dont know',
    'uhhh try again',
    'cant guarantee it',
    '<:ben:948262294402531348> no', // ben
    'naur',
    'i dont think so',
    'yikes',
  ],

  beggars: [
    'a homeless person',
    'Elon Musk',
    'your mother',
    'your father',
    'Donald Trump',
    'i',
    'Low Tier God',
    'Doge',
    'Ben Shapiro',
    'Mr. Krabs',
    'aw hell naw my boy spunch bop',
    'Jonesy',
    'Eminem',
    'mocha',
    'some guy',
    'the impostor from among us',
    'ma man failes',
    'SkyBlueSeagull',
    'NBA Youngboy',
    'Chris Pratt',
    'CJ',
    'Patrick Bateman',
    'Soulja Boy',
    'Snoop Dogg',
    'sans undertale',
    'Jimmy Neutron',
    'Rick Astley',
    'Ayman',
    'Will Smith',
    'Schlatt',
    'Jambo',
    'Wheels',
    'your oomfie',
    'your mutual',
    'the killer fish from san diego',
    'John Wick',
    'John Cena',
    'The Rock',
    'Minecraft Steve',
    'a Minecraft Villager',
    'a Piglin',
    'goopert',
    'King Bach',
    'Tyler Fortnite Ninja Blevins',
    'Fortnite Wife',
    'Foundation',
    'PETA',
    'u/dankmemez23130980',
    'Shrek',
    'Hillary Clinton',
    'an ugly fuckin cat',
    'Mariah Carey',
    'Faileses himself',
    'crewmate',
    'JACOB',
    'Mr Black',
    'Mr. White',
    'Heisenburg',
    'Walter White',
    'JESSE',
    'Gus',
    'bat man',
    'joker',
    'society',
    'Mario',
    'Luigi',
    'Waluigi',
    'Dream',
    'Justin Trudeau',
    'Obama',
    'Slenderman',
    'CSGO Terrorist',
    'CSGO Counter-Terrorist',
    'CSGO Hostage',
    'Twitter',
    'DaBaby',
    'Jar Jar Binks',
    'Joe',
    'Joe Biden',
    'Peter Griffin',
    'Dr. Michael Morbius',
    'Lebron James',
    'Goku fortnite',
    'The Bronze Jade',
    'Jimmy McGill',
    'Saul Goodman',
    'Saul Badman',
    'Glenn Quagmire',
    'black ops 3 title screen guy',
    'Graggle Simpson',
    'Mr. Incredible',
    'Uncanny Mr. Incredible',
    'mr fortnite, the creator of fortnite',
    'the dirt man',
    'jojo',
    'red angry bird',
    'Neco Arc',
    'Wii Fit Trainer',
    'Meowscles',
    'Spiderman-2099',
    'Miles Morales',
    'Meowles Morales',
    'Zavala',
    'Builderman',
    'Mr. Worldwide',
    '2x4 Red Lego Brick #3001',
    'Hank Schrader',
    'Llamar Davis',
    'berbdabee',
    'a lootbug',
    'Toriel'
  ],

  begActions: {
    successful: [
      'gave you',
      'tipped you',
      'handed you',
      'brought you',
      'tossed you',
      'gifted you',
      'loaned you',
      'gave you a small loan of',
      'handed you a briefcase containing',
      'awarded you a whopping',
      'presented you with',
      'gave you a reddit gold and',
      'gave you a reddit platinum and',
      'gave you a reddit silver and',
    ],
    unsuccessful: [
      'robbed you of',
      'ran away with',
      'pickpocketed you of your',
      'stole your',
      'bullied you into giving',
      'took your',          
  ]},

  dailyEvents: {
    bills: {
      message: 'ouch! you\'re super behind on your bills!\n*100 coins from your daily were paid to compensate*\n\n',
      amount: 100,
      chance: 0.1,
    },
    rob: {
      message: 'oh no! you\'ve been robbed!\n*600 coins were found missing from your wallet*\n\n',
      amount: 600,
      chance: 0.1,
    },
    gas: {
      message: 'you ran out of gas on the way to collect your money\n*50 coins were paid at the gas station*\n\n',
      amount: 50,
      chance: 0.1,
    },
    lost: {
      message: 'yikes! looks like you\'ve dropped some of your money somewhere\n*300 coins were missing*\n\n',
      amount: 300,
      chance: 0.1,
    },
  }
}

